cls
/*==================================================

Proiect:		劳动力人力资本数量、质量与经济增长 - 劳动年龄人口
Author:			liuziyu
Create Date:	2023.12
Edit Date:		2024.10.13

--------------------------------------------------

This script is for: 
	1) generating long data of 4-fold population,  
	2) generating 
		long data of 3-fold [urban/gender/age], 
		2-fold population [urban/gender], 
		1-fold population [urban] and [gender],
		0-fold population(province_level pop data),  
	3) merging 3-fold pop with macro data, 
	4) merging 4-fold pop with macro data.

Data source: 
	1) pop data from CHLR, 
	2) macro data generated by 0_Macro.do

==================================================*/

*---0 Program set up
cd "D:\# Library\1 Seminar\1_Publishs\1031-认知技能\data\9_myscript"
do config.do

*---1 generating long data of 4-fold population [urban/gender/age/edu_year] with macro data 
cd "$scriptdir\function\generate"
do gen_pop4.do 

*---2 generating long data of 
*     	3-fold [urban/gender/age] with macro data , 
*     	2-fold population [urban/gender] with macro data , 
*     	1-fold population [urban] and [gender] with macro data , 
*     	0-fold population(province_level pop data) with macro data 
cd "$scriptdir\function\generate"
do gen_pop321.do
